services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway
      POSTGRES_DB: gateway
    ports:
      - '5432:5432'
    volumes:
      - gateway-postgres:/var/lib/postgresql/data
volumes:
  gateway-postgres:
